version: "3"
services:
  app1:
    image: saitejachintakunta/app1:v1
    ports:
      - "8082:8080"
    deploy:
      replicas: 3
  app2:
    image: saitejachintakunta/app2:v2
    ports:
      - "8083:8080"
    deploy:
      replicas: 3
