version: "3"
services:
  app1:
    image: saitejachintakunta/swarm1:26.05
    ports:
      - "8082:8080"
    deploy:
      replicas: 3
  app2:
    image: saitejachintakunta/swarm2:26.05
    ports:
      - "8083:8080"
    deploy:
      replicas: 3
